---
title: "Vizualization"
author: "Gabriel Daldegan"
date: "April 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Scatterplot

```{r load, results= 'hide', echo=TRUE, eval=TRUE}
library(dplyr)
#install.packages("ggplot2")
library(ggplot2)
library(gapminder)

# preview data
gapminder

# get range of available data
summary(gapminder)

```

```{r}
# setup dataframe
g = gapminder %>%
  filter(year==2007) %>%   # most recent year 
  mutate(pop_m = pop/1e6)  # population, millions

# plot scatterplot of most recent year 
s = ggplot(g, aes(x=gdpPercap, y=lifeExp)) +
  #geom_point()
  geom_smooth()
s
s + geom_smooth()

# add aesthetic of size by population
s = s + 
  aes(size=pop_m)
s

# add aesthetic of color by continent
s = s + 
  aes(color=continent)
s

# add title, update axes labels
s = s + 
  ggtitle('Health & Wealth of Nations for 2007') +
  xlab('GDP per capita ($/year)') +
  ylab('Life expectancy (years)')
s

# label legend
s = s + 
  scale_colour_discrete(name='Continent') +
  scale_size_continuous(name='Population (M)')
s

ggsave('hans.png')
```

